SELECT  P.ANHO ANHO, 
	          	P.ORGA_ID ORGANISMO, 
       		  	P.PAGO_ID ORDEN, 
       		  	DECODE(PI.AUTORIZADO_ID, NULL, PI.CTA_BANC_BENEF, PI.CTA_BANC_AUTORI) CUENTA, 
	   		  	DECODE(PI.AUTORIZADO_ID, NULL, PI.INFN_COD_BENEF, PI.INFN_COD_AUTORI) COD_BCO, 
 	   		  	DECODE(PI.AUTORIZADO_ID, NULL, PI.BANCO_BENEF, PI.BANCO_AUTORI) BANCO, 
       		  	PI.MONTO_NETO MONTO, 
				SP.FECHA_MODIF FECHA_MODIFICACION, 
       		  	DECODE(P.RAZON_ID_FIN,0,'EMITIDA',5,'ASOCIADA CTA',2,'PRESELECCIONADA',1,'VALIDADA') ESTADO, 
       		  	DECODE(PI.AUTORIZADO_ID,NULL,PI.NOMBRE_BENEF||' '||PI.APELLIDO_BENEF,PI.NOMBRE_AUTORI||' '||PI.APELLIDO_AUTORI) BENEFICIARIO, 
	   		  	PI.IDENT_BENEF RIF, 
       		  	PI.OBSERVACION 
FROM PAGO P, 
     PAGO_IMPUTADO PI, 
	 PERSONA PE, 
	 SEGUIMIENTO_PAGO SP 
WHERE P.PAGO_ID  = PI.PAGO_ID 
  AND PI.PERS_ID_BENEF=PE.PERS_ID 
  AND P.ANHO     = PI.ANHO 
  AND P.ORGA_ID  = PI.ORGA_ID 
  AND P.TIPG_ID  = PI.TIPG_ID 
  AND P.ANHO	= SP.ANHO 
  AND P.PAGO_ID	= SP.PAGO_ID 
  AND P.ORGA_ID	= SP.ORGA_ID 
  AND P.TIPG_ID = SP.TIPG_ID 
--  AND SP.RAZON_ID IN (0,1,2,5) 
  AND P.TIPG_ID IN (1,9,10) 
  AND P.RAZON_ID_FIN IN (0,1,2,5) 
  AND P.ANHO >= 2018 
  AND TO_DATE(SP.FECHA_MODIF,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR')
  AND Sp.segui_id = (SELECT MAX(segui_id) 
                      FROM seguimiento_pago B 
                     WHERE Sp.pago_id = b.pago_id 
                       AND Sp.anho = b.anho 
                       AND Sp.orga_id = b.orga_id 
                       AND Sp.tipg_id = b.tipg_id) 
UNION 
SELECT 	 P.ANHO ANHO, 
       	 P.ORGA_ID ORGANISMO, 
       	 P.PAGO_ID ORDEN, 
		 DECODE(PI.AUTORIZADO_ID, NULL, PI.CTA_BANC_BENEF, PI.CTA_BANC_AUTORI) CUENTA, 
	   	 DECODE(PI.AUTORIZADO_ID, NULL, PI.INFN_COD_BENEF, PI.INFN_COD_AUTORI) COD_BCO, 
 	   	 DECODE(PI.AUTORIZADO_ID, NULL, PI.BANCO_BENEF, PI.BANCO_AUTORI) BANCO, 
		 PI.MONTO_TOTAL MONTO, 
		 SP.FECHA_MODIF FECHA_MODIFICACION, 
		 DECODE(P.RAZON_ID_FIN,0,'EMITIDA',5,'ASOCIADA CTA',2,'PRESELECCIONADA',1,'VALIDADA') ESTADO, 
       			DECODE(PI.AUTORIZADO_ID,NULL,PI.NOMBRE_BENEF||' '||PI.APELLIDO_BENEF,PI.NOMBRE_AUTORI||' '||PI.APELLIDO_AUTORI) BENEFICIARIO, 
				PI.IDENT_BENEF RIF, 
       			PI.OBSERVACION 
FROM 	PAGO P, 
     	PAGO_NO_IMPUTADO PI, 
		PERSONA PE, 
	  	SEGUIMIENTO_PAGO SP 
WHERE P.PAGO_ID  = PI.PAGO_ID 
  AND PI.PERS_ID_BENEF=PE.PERS_ID 
  AND P.ANHO     = PI.ANHO 
  AND P.ORGA_ID  = PI.ORGA_ID 
  AND P.TIPG_ID  = PI.TIPG_ID 
  AND P.ANHO	= SP.ANHO 
  AND P.PAGO_ID	= SP.PAGO_ID 
  AND P.ORGA_ID	= SP.ORGA_ID 
  AND P.TIPG_ID = SP.TIPG_ID 
--  AND SP.RAZON_ID IN (0,1,2,5) 
  AND P.TIPG_ID IN (1,9,10) 
  AND P.RAZON_ID_FIN IN (0,1,2,5) 
  AND P.ANHO >= 2018 
  AND TO_DATE(SP.FECHA_MODIF,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR')  
  AND Sp.segui_id = (SELECT MAX(segui_id) 
                      FROM seguimiento_pago B 
                     WHERE Sp.pago_id = b.pago_id 
                       AND Sp.anho = b.anho 
                       AND Sp.orga_id = b.orga_id 
                       AND Sp.tipg_id = b.tipg_id) 
  ORDER BY 1,2 ASC