----- *** ORDENES ESTATUS DIVISAS A BOLIVARES  *** -----
SELECT P.ANHO ANHO,
       P.RAZON_ID_FIN ESTADO,
       P.FECHA_PAGO PAGADA,
       P.ORGA_ID ORGANISMO,
       P.PAGO_ID ORDEN,
       SUM(DPI.MONTO_NETO) MONTO_PAGADO,     
       --DPI.PLUC_ID PARTIDA,
       SP.RAZON_ID ESTADO2,
       UPPER(DECODE(PI.AUTORIZADO_ID,NULL,PI.NOMBRE_BENEF||' '||PI.APELLIDO_BENEF,PI.NOMBRE_AUTORI||' '||PI.APELLIDO_AUTORI)) BENEFICIARIO,      
       PI.OBSERVACION
FROM PAGO P, PAGO_IMPUTADO PI, DET_PAGO_IMPUTADO DPI,SEGUIMIENTO_PAGO SP--,PLAN_UNICO_CTA PU
WHERE P.PAGO_ID = PI.PAGO_ID
  AND P.ANHO     = PI.ANHO
  AND P.ORGA_ID = PI.ORGA_ID
  AND P.TIPG_ID = PI.TIPG_ID
  --AND DPI.PLUC_ID=PU.PLUC_ID
  --AND DPI.ANHO=PU.ANHO
  AND PI.PAGO_ID = DPI.PAGO_ID
  AND PI.ANHO      = DPI.ANHO
  AND PI.ORGA_ID = DPI.ORGA_ID
  AND PI.TIPG_ID = DPI.TIPG_ID
  AND P.ANHO    = SP.ANHO
  AND P.PAGO_ID    = SP.PAGO_ID
  AND P.ORGA_ID    = SP.ORGA_ID
  AND P.TIPG_ID = SP.TIPG_ID
  --AND P.ANHO IN (2024,2025)
  AND P.RAZON_ID_FIN = 12
  AND SP.RAZON_ID = 11  
  AND P.TIPG_ID IN (1)
  AND TO_DATE(FECHA_PAGO,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR')
GROUP BY P.ANHO,
           P.RAZON_ID_FIN,
         P.FECHA_PAGO,         
           P.ORGA_ID,
         P.PAGO_ID,
         --DPI.PLUC_ID,
         SP.RAZON_ID,
         UPPER(DECODE(PI.AUTORIZADO_ID,NULL,PI.NOMBRE_BENEF||' '||PI.APELLIDO_BENEF,PI.NOMBRE_AUTORI||' '||PI.APELLIDO_AUTORI)),
         PI.OBSERVACION,
         TO_CHAR(P.FECHA_PAGO,'MM/RRRR')
ORDER BY 1,2,3 ASC  