SELECT ORGANISMO, PARTIDAS, SUM(ANHO_ANTERIOR) ANHO_ANTERIOR, SUM(ANHO_ACTUAL) ANHO_ACTUAL, SUM(ANHO_ANTERIOR)+SUM(ANHO_ACTUAL) MONTO_TOTAL 
FROM ( 
	  SELECT P.ORGA_ID ORGANISMO, UPPER(PART.PART_ID||' - '||PART.DENOMINACION) PARTIDAS, SUM(DPI.MONTO_BRUTO) ANHO_ANTERIOR, 0 ANHO_ACTUAL 
	  FROM PAGO P, DET_PAGO_IMPUTADO DPI, PARTIDA PART 
	  WHERE P.ANHO = DPI.ANHO 
	    AND P.ORGA_ID = DPI.ORGA_ID 
  		AND P.PAGO_ID = DPI.PAGO_ID 
  		AND P.TIPG_ID = DPI.TIPG_ID 
  		AND P.TIPG_ID IN (1,9,10) 
		AND SUBSTR(DPI.PLUC_ID,1,3) = PART.PART_ID 
		AND PART.ANHO = P.ANHO 
	    AND P.RAZON_ID_FIN IN (4,12) 
  		AND P.ANHO = TO_NUMBER(TO_CHAR(SYSDATE,'RRRR'))-1 
		AND (TO_DATE(P.FECHA_PAGO,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR'))  
	  GROUP BY P.ORGA_ID,PART.PART_ID||' - '||PART.DENOMINACION	   	  
	  UNION	   	  
	  SELECT P.ORGA_ID ORGANISMO,'FOND'||' - '||TF.DENOMINACION PARTIDAS, SUM(PNI.MONTO_TOTAL) MONTO_ANTERIOR, 0 MONTO_ACTUAL 
	  FROM PAGO P, PAGO_NO_IMPUTADO PNI, TIPO_FONDO TF 
	  WHERE P.ANHO = PNI.ANHO 
	    AND P.ORGA_ID = PNI.ORGA_ID 
  		AND P.PAGO_ID = PNI.PAGO_ID 
  		AND P.TIPG_ID = PNI.TIPG_ID 
  		AND P.TIPG_ID IN (1,9,10) 
        AND PNI.TIFO_ID = TF.TIFO_ID 
	    AND P.RAZON_ID_FIN IN (4,12) 			   
  		AND P.ANHO = TO_NUMBER(TO_CHAR(SYSDATE,'RRRR'))-1 
		AND (TO_DATE(P.FECHA_PAGO,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR'))  
	  GROUP BY P.ORGA_ID,'FOND'||' - '||TF.DENOMINACION 	  
	  UNION	   	  
 	  SELECT P.ORGA_ID ORGANISMO,UPPER(PART.PART_ID||' - '||PART.DENOMINACION) PARTIDAS, 0 ANHO_ANTERIOR, SUM(DPI.MONTO_BRUTO) ANHO_ACTUAL 
	  FROM PAGO P, DET_PAGO_IMPUTADO DPI, PARTIDA PART 
	  WHERE P.ANHO = DPI.ANHO 
	    AND P.ORGA_ID = DPI.ORGA_ID 
  		AND P.PAGO_ID = DPI.PAGO_ID 
  		AND P.TIPG_ID = DPI.TIPG_ID 
  		AND P.TIPG_ID IN (1,9,10) 
		AND SUBSTR(DPI.PLUC_ID,1,3) = PART.PART_ID 
		AND PART.ANHO = P.ANHO 
	    AND P.RAZON_ID_FIN IN (4,12) 
  		AND P.ANHO = TO_NUMBER(TO_CHAR(SYSDATE,'RRRR')) 
		AND (TO_DATE(P.FECHA_PAGO,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR'))  
	  GROUP BY P.ORGA_ID,PART.PART_ID||' - '||PART.DENOMINACION 	  	  
	  UNION 	  	  
	  SELECT P.ORGA_ID ORGANISMO,'FOND'||' - '||TF.DENOMINACION PARTIDAS, 0 ANHO_ANTERIOR, SUM(PNI.MONTO_TOTAL) ANHO_ACTUAL 
	  FROM PAGO P, PAGO_NO_IMPUTADO PNI, TIPO_FONDO TF 
	  WHERE P.ANHO = PNI.ANHO 
	    AND P.ORGA_ID = PNI.ORGA_ID 
  		AND P.PAGO_ID = PNI.PAGO_ID 
  		AND P.TIPG_ID = PNI.TIPG_ID 
  		AND P.TIPG_ID IN (1,9,10) 
        AND PNI.TIFO_ID = TF.TIFO_ID 
		AND P.RAZON_ID_FIN IN (4,12) 			   
  		AND P.ANHO = TO_NUMBER(TO_CHAR(SYSDATE,'RRRR')) 
		AND (TO_DATE(P.FECHA_PAGO,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR')) 	         
	  GROUP BY P.ORGA_ID,'FOND'||' - '||TF.DENOMINACION)	   
GROUP BY ORGANISMO,PARTIDAS 
ORDER BY ORGANISMO,PARTIDAS