SELECT 
		ROWNUM AS ID_SECUENCIAL, 
	   	UPPER(REPLACE(DECODE(PI.AUTORIZADO_ID, NULL, PI.IDENT_BENEF, PI.IDENT_AUTORI),'-','')) AS RIF_RETENIDO, 
		'T'||TO_CHAR(P.FECHA_PAGO, 'RR')||P.ORGA_ID||LPAD(P.PAGO_ID,'5','0') AS NUMERO_FACTURA, 
		'T'||TO_CHAR(P.FECHA_PAGO, 'RR')||P.ORGA_ID||LPAD(P.PAGO_ID,'5','0') AS NUMERO_CONTROL, 
		 TO_DATE(P.FECHA_PAGO,'DD/MM/RRRR') FECHA_PAGO, 
		 DECODE(UPPER(SUBSTR(DECODE(PI.AUTORIZADO_ID, NULL, PI.IDENT_BENEF, PI.IDENT_AUTORI),1,1)), 'J', '055', 'G', '055', '053') AS CODIGO_CONCEPTO, 
		 CORE.MONTO MONTO_DOCUMENTO, 
--	  	((R.MONTO+DECODE(UPPER(SUBSTR(DECODE(PI.AUTORIZADO_ID, NULL, PI.IDENT_BENEF, PI.IDENT_AUTORI),1,1)), 'J', 0, 'G', 0, (9*0.01*83.3334))))/(DECODE(UPPER(SUBSTR(DECODE(PI.AUTORIZADO_ID, NULL, PI.IDENT_BENEF, PI.IDENT_AUTORI),1,1)), 'J', 0.02, 'G', 0.02, 0.01)) AS MONTO_OPERACION, 
--	  	 DECODE(UPPER(SUBSTR(DECODE(PI.AUTORIZADO_ID, NULL, PI.IDENT_BENEF, PI.IDENT_AUTORI),1,1)), 'J', 2, 'G', 2, 1) AS PROCENTAJE_RETENCION, 
		 CORE.ALICUOTA PORCENTAJE_RETENCION, 
     	 R.MONTO AS RETENCION_ISLR, 
		 'G200043490' RIF_CONTRIBUYENTE, 
         TO_CHAR(P.FECHA_PAGO,'RRRRMM') PERIODO_IMPOSITIVO, 
		 P.ANHO ANHO_PRESUPUESTARIO, 
		 P.PAGO_ID NRO_OP, 
		 o.orga_id||' '||o.denominacion organismo, 
		 REPLACE(REPLACE(REPLACE(O.RIF,'-',''),' ',''),'.','') RIF_ORGANISMO, 
	   	 pi.unad_id cod_unidad_administradora, 
	   	 ua.denominacion desc_unidad_administradora, 
         r.RETE_ID||'-'||rt.DENOMINACION TIPO_RETENCION, 
		 PI.NOMBRE_BENEF||' '||PI.APELLIDO_BENEF  BENEFICIARIO, 
		 REPLACE(REPLACE(REPLACE(PI.IDENT_BENEF,'-',''),' ',''),'.','') RIF_BENEFICIARIO, 
		 PI.NOMBRE_AUTORI||' '||PI.APELLIDO_AUTORI AUTORIZADO, 
		 REPLACE(REPLACE(REPLACE(PI.IDENT_AUTORI,'-',''),' ',''),'.','') RIF_AUTORIZADO, 
         TO_CHAR(P.FECHA_PAGO,'RRRRMM')||LPAD(ROWNUM,8,'0') NUMERO_COMPROBANTE, 
		 PASI.FECHA_FACTURA, 
		 PASI.NRO_DOC NUM_FACTURA, 
		 PASI.NRO_CONTROL NUM_CONTROL, 
		 PI.OBSERVACION OBSERVACION 
	   FROM PAGO P, 
	   		PAGO_IMPUTADO PI, 
			RETENCION_X_PAGO R, 
			retencion rt, 
		    organismo o, 
			unidad_administradora ua, 
			COMPROBANTE_RETENCION CORE, 
 	 		DET_CAUSADO_X_DOC PASI 
	   WHERE P.ANHO = PI.ANHO 
	   AND P.ORGA_ID = PI.ORGA_ID 
	   AND P.PAGO_ID = PI.PAGO_ID 
	   AND P.TIPG_ID = PI.TIPG_ID 
	   AND P.PAGO_ID = R.PAGO_ID 
	   AND P.ANHO = R.ANHO 
	   AND P.ORGA_ID = R.ORGA_ID 
	   AND P.TIPG_ID = R.TIPG_ID 
 	   AND p.orga_id = o.orga_id 
	   AND ua.unad_id = pi.unad_id 
	   AND ua.anho = pi.anho 
	   AND ua.orga_id = pi.orga_id 
	   AND R.RETE_ID = Rt.RETE_ID 
  	   AND R.ORGA_ID = Rt.ORGA_ID 
  	   AND CORE.ORGA_ID=P.ORGA_ID 
  	   AND CORE.PAGO_ID=P.PAGO_ID 
  	   AND CORE.TIPG_ID=P.TIPG_ID 
  	   AND core.ANHO=p.ANHO 
  	   AND CORE.ANHO = PASI.ANHO 
  	   AND CORE.CAUS_ID = PASI.CAUS_ID 
  	   AND CORE.CAUS_EXPEDIENTE = PASI.EXPEDIENTE 
  	   AND CORE.ORGA_ID = PASI.ORGA_ID 
  	   AND core.TIRE_ID IN (2) 
	   AND P.TIPG_ID IN (1,10) 
	   AND P.RAZON_ID_FIN IN (4,12,11,13) 
	   AND TO_DATE(P.FECHA_PAGO,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR') 
	   ORDER BY 14 ASC