SELECT  ANHO,ORGANISMO,FUENTE,PARTIDA,FONDO,ORDEN,ESTADO,MONTO_LEY,CREDITO_ADICIONAL,BENEFICIARIO,AUTORIZADO,PAGADA,FECHA_MODIFICACION,CUENTA,OBSERVACION,SUM(MONTO) MONTO 
FROM ( 
SELECT P.ANHO ANHO, 
 	   P.PAGO_ID ORDEN, 
	   P.RAZON_ID_FIN ESTADO, 
	   PA.PRESUPUESTO_LEY MONTO_LEY, 
	   PA.CREDITO_ADICIONAL CREDITO_ADICIONAL, 
	   PA.NOMBRE_BENEF||' '||PA.APELLIDO_BENEF BENEFICIARIO, 
	   PA.NOMBRE_AUTORI||' '||PA.APELLIDO_AUTORI AUTORIZADO, 
	   P.FECHA_PAGO PAGADA, 
	   SP.FECHA_MODIF FECHA_MODIFICACION, 
	   DECODE(PA.AUTORIZADO_ID, NULL, PA.CTA_BANC_BENEF, PA.CTA_BANC_AUTORI) CUENTA, 
	   UPPER(P.ORGA_ID||' - '||O.DENOMINACION) ORGANISMO, 
	   UPPER(F.FFIN_ID||' - '||F.DENOMINACION) FUENTE, 
	   UPPER(PU.PLUC_ID||' - '||PU.DENOMINACION) PARTIDA, 
	   '' FONDO, 
	   PA.OBSERVACION, 
	   SUM(PI.MONTO_NETO) MONTO 
FROM PAGO P, 
	 DET_PAGO_IMPUTADO PI, 
	 ORGANISMO O,
	 PLAN_UNICO_CTA PU, 
	 FUENTE_FINANCIAMIENTO F,
	 PAGO_IMPUTADO PA ,
	 SEGUIMIENTO_PAGO SP 
WHERE P.PAGO_ID = PI.PAGO_ID 
  AND P.ANHO = PI.ANHO 
  AND P.ANHO=PU.ANHO 
  AND P.ORGA_ID = PI.ORGA_ID 
  AND P.TIPG_ID = PI.TIPG_ID 
  AND P.ANHO=PA.ANHO 
  AND P.ORGA_ID=PA.ORGA_ID 
  AND P.PAGO_ID=PA.PAGO_ID 
  AND P.TIPG_ID=PA.TIPG_ID 
  AND P.ORGA_ID = O.ORGA_ID 
  AND PI.PLUC_ID = PU.PLUC_ID 
  AND PI.FFIN_ID = F.FFIN_ID 
  AND P.ANHO	= SP.ANHO 
  AND P.PAGO_ID	= SP.PAGO_ID 
  AND P.ORGA_ID	= SP.ORGA_ID 
  AND P.TIPG_ID = SP.TIPG_ID 
  AND SP.RAZON_ID IN (4,11,12) 
  AND P.TIPG_ID IN (1,9,10) 
  AND (pa.CTA_BANC_AUTORI = '0001-0001-36-4429002017' OR pa.CTA_BANC_BENEF = '0001-0001-36-4429002017')
  AND Sp.segui_id = (SELECT MAX(segui_id) 
                      FROM seguimiento_pago B 
                     WHERE Sp.pago_id = b.pago_id 
                       AND Sp.anho = b.anho 
                       AND Sp.orga_id = b.orga_id 
                       AND Sp.tipg_id = b.tipg_id)     
 AND TO_DATE(SP.FECHA_MODIF,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR') 
GROUP BY P.ANHO, 
	  	 P.PAGO_ID, 
		 P.RAZON_ID_FIN, 
	   	 PA.PRESUPUESTO_LEY, 
	   	 PA.CREDITO_ADICIONAL, 
	   	 PA.NOMBRE_BENEF||' '||PA.APELLIDO_BENEF, 
	   	 PA.NOMBRE_AUTORI||' '||PA.APELLIDO_AUTORI, 
		 P.FECHA_PAGO, 
		 SP.FECHA_MODIF, 
	   	 DECODE(PA.AUTORIZADO_ID, NULL, PA.CTA_BANC_BENEF, PA.CTA_BANC_AUTORI), 
		 UPPER(P.ORGA_ID||' - '||O.DENOMINACION), 
		 UPPER(F.FFIN_ID||' - '||F.DENOMINACION), 
		 UPPER(PU.PLUC_ID||' - '||PU.DENOMINACION), 
		 PA.OBSERVACION 
) 
GROUP BY ANHO,ORGANISMO,FUENTE,PARTIDA,FONDO,ORDEN,ESTADO,MONTO_LEY,CREDITO_ADICIONAL,BENEFICIARIO,AUTORIZADO,PAGADA,FECHA_MODIFICACION,CUENTA,OBSERVACION 
ORDER BY 1,2 ASC