SELECT 
    REPLACE(REPLACE(REPLACE(O.RIF,'-',''),' ',''),'.','') AS RIF_CONTRIBUYENTE, 
    TO_CHAR(P.FECHA_PAGO,'RRRRMM') PERIODO_IMPOSITIVO, 
    TO_CHAR(P.FECHA_PAGO,'RRRR-MM-DD') FECHA_DOCUMENTO, 
    'C' TIPO_OPERACION, 
    '01' TIPO_DOCUMENTO, 
    o.orga_id||' '||o.denominacion organismo, 
    REPLACE(REPLACE(REPLACE(O.RIF,'-',''),' ',''),'.','') RIF_ORGANISMO, 
    pi.unad_id cod_unidad_administradora, 
    ua.denominacion desc_unidad_administradora, 
    r.RETE_ID||'-'||rt.DENOMINACION TIPO_RETENCION, 
    PI.NOMBRE_BENEF||' '||PI.APELLIDO_BENEF  BENEFICIARIO,
    REPLACE(REPLACE(REPLACE(PI.IDENT_BENEF,'-',''),' ',''),'.','') RIF_BENEFICIARIO,
    PI.NOMBRE_AUTORI||' '||PI.APELLIDO_AUTORI AUTORIZADO,
    REPLACE(REPLACE(REPLACE(PI.IDENT_AUTORI,'-',''),' ',''),'.','') RIF_AUTORIZADO, 
    REPLACE(REPLACE(REPLACE(DECODE(AUTORIZADO_ID, NULL, IDENT_BENEF, IDENT_AUTORI),'-',''),' ',''),'.','') RIF_VENDEDOR, 
    'OP'||LPAD(P.ANHO||P.ORGA_ID||P.PAGO_ID,'18',0) NUMERO_DOCUMENTO, 
    'OP'||LPAD(P.ANHO||P.ORGA_ID||P.PAGO_ID,'18',0) NUMERO_CONTROL_DOCUMENTO, 
    PI.MONTO_BRUTO MONTO_TOTAL_DOCUMENTO, 
    CORE.BASE_IMPONIBLE, 
    CORE.ALICUOTA,
    PASI.FECHA_FACTURA,
    PASI.NRO_DOC NUM_FACTURA,
    PASI.NRO_CONTROL NUM_CONTROL,
    r.MONTO MONTO_IVA, 
    '0' NUMERO_DOCUMENTO_AFECTADO, 
    TO_CHAR(P.FECHA_PAGO,'RRRRMM')||LPAD(ROWNUM,8,'0') NUMERO_COMPROBANTE, 
    '0' MONTO_EXCENTO_IVA, 
    '0' NUMERO_EXPEDIENTE 
FROM PAGO P, 
    PAGO_IMPUTADO PI, 
    RETENCION_X_PAGO R, 
    retencion rt, 
    unidad_administradora ua , 
    organismo o, 
    COMPROBANTE_RETENCION CORE,
    DET_CAUSADO_X_DOC PASI	 
WHERE P.ANHO = PI.ANHO 
    AND P.ORGA_ID = PI.ORGA_ID 
    AND P.PAGO_ID = PI.PAGO_ID 
    AND P.TIPG_ID = PI.TIPG_ID 
    AND PI.ANHO = R.ANHO 
    AND PI.ORGA_ID = R.ORGA_ID 
    AND PI.PAGO_ID = R.PAGO_ID 
    AND PI.TIPG_ID = R.TIPG_ID 
    AND R.RETE_ID = Rt.RETE_ID 
    AND R.ORGA_ID = Rt.ORGA_ID 
    AND p.orga_id = o.orga_id 
    AND ua.unad_id = pi.unad_id 
    AND ua.anho = pi.anho 
    AND ua.orga_id = pi.orga_id 
    AND CORE.ORGA_ID = P.ORGA_ID 
    AND CORE.PAGO_ID = P.PAGO_ID 
    AND CORE.TIPG_ID = P.TIPG_ID 
    AND core.ANHO = p.ANHO 
    AND CORE.ANHO = PASI.ANHO
    AND CORE.CAUS_ID = PASI.CAUS_ID
    AND CORE.CAUS_EXPEDIENTE = PASI.EXPEDIENTE
    AND CORE.ORGA_ID = PASI.ORGA_ID  
    AND core.TIRE_ID IN (1) 
    AND P.TIPG_ID IN (1,10) 
    AND P.RAZON_ID_FIN IN (4,11,12)   
    -- Filtro por RIF del contribuyente (organismo pagador)
    AND REPLACE(REPLACE(REPLACE(O.RIF,'-',''),' ',''),'.','') = :rif
ORDER BY fecha_documento