-----**** ORDENES PAGADAS PROGRAMACION FINANCIERA *****-----------
----**********************************************************-----------

SELECT PRESUPUESTO,ORGANISMO,ORDEN,SUM(MONTO_NETO) MONTO_NETO,ESTADO,TO_CHAR(PAGADA,'DD/MM/RRRR')FECHA_PAGO, SUBSTR(PARTIDA,1,3) PARTIDA,BENEFICIARIO,  MONEDA, 'BCV' LUGAR, OBSERVACION
FROM (
SELECT P.ANHO PRESUPUESTO,
 	   P.PAGO_ID ORDEN,
	   P.RAZON_ID_FIN ESTADO,
	   P.FECHA_PAGO PAGADA,
	   P.CODIGO_MONEDA MONEDA,
	   DECODE(PA.AUTORIZADO_ID,NULL,PA.NOMBRE_BENEF||' '||PA.APELLIDO_BENEF,PA.NOMBRE_AUTORI||' '||PA.APELLIDO_AUTORI) BENEFICIARIO,
	   DECODE(PA.AUTORIZADO_ID, NULL, PA.CTA_BANC_BENEF, PA.CTA_BANC_AUTORI) CUENTA,
	   UPPER(P.ORGA_ID) ORGANISMO,
	   UPPER (O.DENOMINACION) ORGA_DENOMINACION,
	   --UPPER(F.FFIN_ID||' - '||F.DENOMINACION) FUENTE,
	   UPPER(PU.PLUC_ID||' - '||PU.DENOMINACION) PARTIDA,
	   --'' FONDO,
	   SUM(PI.MONTO_NETO) MONTO_NETO,
	   SUM(PA.MONTO_BRUTO) MONTO_BRUTO,
	   e.codigo||' - '||per.nombre ente_receptor,
	   PA.OBSERVACION
FROM PAGO P, ORGANISMO O,DET_PAGO_IMPUTADO PI, PLAN_UNICO_CTA PU, FUENTE_FINANCIAMIENTO F,PAGO_IMPUTADO PA, ENTE_RECEPTOR E, PERSONA PER
WHERE P.PAGO_ID = PI.PAGO_ID
  AND P.ANHO = PI.ANHO
  AND P.ANHO=PU.ANHO
  AND P.ORGA_ID = PI.ORGA_ID
  AND P.TIPG_ID = PI.TIPG_ID
  AND P.ANHO=PA.ANHO
  AND P.ORGA_ID=PA.ORGA_ID
  AND P.PAGO_ID=PA.PAGO_ID
  AND P.TIPG_ID=PA.TIPG_ID
  AND P.ORGA_ID = O.ORGA_ID
  AND PI.PLUC_ID = PU.PLUC_ID
  AND PI.FFIN_ID = F.FFIN_ID
  AND P.RAZON_ID_FIN IN (4,12)--,11,12,13)
  AND P.TIPG_ID IN (1,9,10)
  AND DECODE(PA.autorizado_id, NULL, PA.pers_id_benef, PA.autorizado_id) = e.pers_id(+)
  AND E.pers_id = per.pers_id(+)
 -- AND P.ANHO IN (2024,2025)
  --and p.orga_id = 034
  --and p.pago_id in ('127','193')
  AND TO_DATE(P.FECHA_PAGO,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR')
GROUP BY P.ANHO,
	  	 P.PAGO_ID,
		 P.RAZON_ID_FIN,
		 P.FECHA_PAGO,
	   	 DECODE(PA.AUTORIZADO_ID, NULL, PA.CTA_BANC_BENEF, PA.CTA_BANC_AUTORI),
		 DECODE(PA.AUTORIZADO_ID,NULL,PA.NOMBRE_BENEF||' '||PA.APELLIDO_BENEF,PA.NOMBRE_AUTORI||' '||PA.APELLIDO_AUTORI),
		 UPPER(P.ORGA_ID),
		 UPPER (O.DENOMINACION),
		 --UPPER(F.FFIN_ID||' - '||F.DENOMINACION),
		 UPPER(PU.PLUC_ID||' - '||PU.DENOMINACION),
		 PA.OBSERVACION, P.CODIGO_MONEDA , e.codigo||' - '||per.nombre
UNION
SELECT P.ANHO PRESUPUESTO,
 	   P.PAGO_ID ORDEN,
	   P.RAZON_ID_FIN ESTADO,
	   P.FECHA_PAGO,
	   P.CODIGO_MONEDA,
	   DECODE(PNI.AUTORIZADO_ID,NULL,PNI.NOMBRE_BENEF||' '||PNI.APELLIDO_BENEF,PNI.NOMBRE_AUTORI||' '||PNI.APELLIDO_AUTORI) BENEFICIARIO,
  	   DECODE(PNI.AUTORIZADO_ID, NULL, PNI.CTA_BANC_BENEF, PNI.CTA_BANC_AUTORI) CUENTA,
	   UPPER(P.ORGA_ID) ORGANISMO,
	   UPPER(O.DENOMINACION),
	   --UPPER(F.FFIN_ID||' - '||F.DENOMINACION) FUENTE,
	   '' PARTIDA,
	   --UPPER(T.TIFO_ID||' - '||T.DENOMINACION) FONDO,
	   SUM(PNI.MONTO_TOTAL) MONTO,
	   SUM(PNI.MONTO_TOTAL) MONTO_BRUTO,
	   e.codigo||' - '||per.nombre ente_receptor,
	   PNI.OBSERVACION
FROM PAGO P, PAGO_NO_IMPUTADO PNI,ORGANISMO O, TIPO_FONDO T, FUENTE_FINANCIAMIENTO F, ENTE_RECEPTOR E, PERSONA PER
WHERE P.PAGO_ID = PNI.PAGO_ID
  AND P.ANHO = PNI.ANHO
  AND P.ORGA_ID = PNI.ORGA_ID
  AND P.TIPG_ID = PNI.TIPG_ID
  AND P.ORGA_ID = O.ORGA_ID
  AND PNI.TIFO_ID = T.TIFO_ID
  AND PNI.FFIN_ID = F.FFIN_ID
  AND P.TIPG_ID IN (1,9,10)
 -- AND P.ANHO IN (2024,2025)
  AND DECODE(PNI.autorizado_id, NULL, PNI.pers_id_benef, PNI.autorizado_id) = e.pers_id(+)
  AND E.pers_id = per.pers_id(+)
  AND P.RAZON_ID_FIN IN (4,12)
  AND TO_DATE(P.FECHA_PAGO,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR')
GROUP BY P.ANHO,
	  	 P.PAGO_ID,
		 P.RAZON_ID_FIN,
		 P.FECHA_PAGO,
  	   	 DECODE(PNI.AUTORIZADO_ID, NULL, PNI.CTA_BANC_BENEF, PNI.CTA_BANC_AUTORI),
		 DECODE(PNI.AUTORIZADO_ID,NULL,PNI.NOMBRE_BENEF||' '||PNI.APELLIDO_BENEF,PNI.NOMBRE_AUTORI||' '||PNI.APELLIDO_AUTORI),
		 UPPER(P.ORGA_ID),
		 UPPER(O.DENOMINACION),
		 --UPPER(F.FFIN_ID||' - '||F.DENOMINACION),
		 --UPPER(T.TIFO_ID||' - '||T.DENOMINACION),
    	 PNI.OBSERVACION, P.CODIGO_MONEDA , e.codigo||' - '||per.nombre
)
GROUP BY PRESUPUESTO,ORGANISMO,ORGA_DENOMINACION,PARTIDA,ORDEN,ESTADO,PAGADA,BENEFICIARIO,CUENTA,OBSERVACION, MONEDA, ENTE_RECEPTOR
ORDER BY 1,2,3 ASC


