--**********************************************************
--******DETALLE TRANSMISION POR DIA********
--**********************************************************
  SELECT E.PAGO_ID,
  		 E.ORGA_ID,
		 O.DENOMINACION,
		 E.FECHA_VALOR,
  		 SUM(E.MONTO) MONTO_TOTAL
  FROM TRANSM_BCV_ENVIO E, TRANSM_BCV_RETORNO R,ORGANISMO O      
  WHERE E.TIPO_ARCHIVO = R.TIPO_ARCHIVO        
    AND E.FECHA_TRANSMISION = R.FECHA_TRANSMISION         
    AND E.INFN_CODIGO = R.INFN_CODIGO
    AND E.NRO_TRANSMISION = R.NRO_TRANSMISION       
    AND E.NRO_DETALLE = R.NRO_DETALLE
	AND E.ORGA_ID=O.ORGA_ID
	--AND e.ANHO IN (2022,2023)
	AND R.RETORNO_CODIGO = '01'    
  AND TO_DATE(E.FECHA_VALOR,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR')
  GROUP BY E.PAGO_ID,
  		 E.ORGA_ID,
		 O.DENOMINACION,
		 E.FECHA_VALOR
ORDER BY 2,1 ASC